apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikro-muhasebe
  namespace: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikro-muhasebe
  template:
    metadata:
      labels:
        app: mikro-muhasebe
    spec:
      containers:
      - name: mikro-muhasebe
        image: DOCKER_IMAGE_NAME
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: DOTNET_RUNNING_IN_CONTAINER
            value: "true"
          - name: ASPNETCORE_URLS
            value: "http://*:8080"
        ports:
          - name: muhasebeservice
            containerPort: 8080
      imagePullSecrets:
      - name: gitlab-registry